#!/usr/bin/env python3
"""
Funding Push Notifier — sends ntfy desktop push notifications for new funding alerts.

Reads output from funding_proposal_with_enrichment.py and pushes to ntfy topics.
Supports multiple channels (e.g., shawnee-funding, jorge-funding).
Enhanced: clickable links for research report, LinkedIn, website, and news article.

Usage:
    python execution/funding_push_notifier.py --input .tmp/funding_results.json
    python execution/funding_push_notifier.py --input .tmp/funding_results.json --topics shawnee-funding,jorge-funding
    python execution/funding_push_notifier.py --test  # send a test notification
    python execution/funding_push_notifier.py --test-rich  # send a rich test with clickable links
"""

import os
import sys
import json
import argparse
from pathlib import Path

import requests

NTFY_BASE = os.environ.get("NTFY_URL", "http://localhost:8080")
DEFAULT_TOPICS = ["jorge-funding"]

# Report links mapping file (generated by shawnee_drive_upload.py)
PROJECT_ROOT = Path(__file__).parent.parent
REPORT_LINKS_FILE = PROJECT_ROOT / "data" / "report_drive_links.json"


def load_report_links() -> dict:
    """Load company -> Drive URL mapping for research reports."""
    if REPORT_LINKS_FILE.exists():
        with open(REPORT_LINKS_FILE, "r", encoding="utf-8") as f:
            return json.load(f)
    return {}


def send_push(topic: str, title: str, message: str, tags: str = "",
              priority: str = "default", click_url: str = None,
              actions: list[str] = None) -> bool:
    """Send a push notification to an ntfy topic.

    Args:
        click_url: URL opened when notification is clicked (e.g., research report)
        actions: List of ntfy action strings for clickable buttons
                 Format: "view, Label, https://url"
    """
    url = f"{NTFY_BASE}/{topic}"
    headers = {
        "Title": title,
        "Priority": priority,
    }

    if tags:
        headers["Tags"] = tags

    if click_url:
        headers["Click"] = click_url

    if actions:
        # ntfy supports up to 3 action buttons
        headers["Actions"] = "; ".join(actions[:3])

    try:
        resp = requests.post(
            url,
            headers=headers,
            data=message.encode("utf-8"),
            timeout=30,
        )
        if resp.ok:
            print(f"  [OK] Push sent to {topic}")
            return True
        else:
            print(f"  [FAIL] {topic}: {resp.status_code} {resp.text[:100]}")
            return False
    except Exception as e:
        print(f"  [ERROR] {topic}: {e}")
        return False


def format_funding_alert(item: dict, report_links: dict = None) -> tuple[str, str, str, list]:
    """Format a funding result into title + body + click_url + actions for push notification.

    Returns:
        (title, body, click_url, actions)
    """
    company = item.get("company", "Unknown")
    amount = item.get("amount", "")
    round_type = item.get("round_type", "")

    # Title
    parts = [company]
    if amount:
        parts.append(f"raised {amount}")
    if round_type:
        parts.append(f"({round_type})")
    title = " ".join(parts)

    # Body with all relevant info
    dm = item.get("decision_maker", {})
    lines = []

    if dm.get("name") and dm["name"] != "there":
        role = dm.get("role", "")
        lines.append(f"Contact: {dm['name']}" + (f" ({role})" if role else ""))

    if dm.get("linkedin_url"):
        lines.append(f"LinkedIn: {dm['linkedin_url']}")

    if dm.get("email"):
        lines.append(f"Email: {dm['email']}")

    if item.get("website"):
        lines.append(f"Website: {item['website']}")

    if item.get("article"):
        lines.append(f"Article: {item['article']}")

    if not lines:
        lines.append(f"New funding detected for {company}")

    body = "\n".join(lines)

    # Click URL — prioritize research report, fall back to article
    click_url = None
    report_url = None

    if report_links:
        # Try to match company name to report
        company_lower = company.lower().replace(' ', ' ')
        for key, data in report_links.items():
            if (company_lower in key or key in company_lower or
                    company_lower.replace(' ', '_') in key or
                    key.replace(' ', '_') in company_lower.replace(' ', '_')):
                report_url = data.get('drive_url', '')
                break

    click_url = report_url or item.get("article", "")

    # Action buttons — order: Open Report, News Article, Founder LinkedIn
    # ntfy supports up to 3 custom action buttons
    actions = []

    # 1. Research report in Google Drive (if available)
    if report_url:
        actions.append(f"view, Open Report, {report_url}")

    # 2. News article that triggered the alert
    article_url = item.get("article", "")
    if len(actions) < 3 and article_url and article_url.startswith("http"):
        actions.append(f"view, News Article, {article_url}")

    # 3. Founder LinkedIn (personal profile, not company page)
    if len(actions) < 3 and dm.get("linkedin_url"):
        name = dm.get("name", "Founder")
        role = dm.get("role", "")
        label = f"{name} ({role})" if role else name
        actions.append(f"view, {label}, {dm['linkedin_url']}")

    return title, body, click_url, actions


def notify_from_results(results_file: str, topics: list[str]) -> int:
    """Read funding results JSON and send push notifications."""
    path = Path(results_file)
    if not path.exists():
        print(f"[WARN] Results file not found: {results_file}")
        return 0

    with open(path, "r", encoding="utf-8") as f:
        results = json.load(f)

    if not results:
        print("[INFO] No new funding results to notify about")
        return 0

    # Load report links for clickable report buttons
    report_links = load_report_links()
    if report_links:
        print(f"[INFO] Loaded {len(report_links)} report Drive links")

    print(f"[INFO] Sending {len(results)} alerts to topics: {', '.join(topics)}")
    sent = 0

    for item in results:
        title, body, click_url, actions = format_funding_alert(item, report_links)
        print(f"\n  Alert: {title}")
        if actions:
            print(f"  Actions: {actions}")
        for topic in topics:
            if send_push(topic, title, body, click_url=click_url, actions=actions):
                sent += 1

    print(f"\n[DONE] Sent {sent} notifications")
    return sent


def send_test(topics: list[str]):
    """Send a test notification to verify the channel works."""
    title = "Funding Monitor Test"
    body = "If you see this, push notifications are working.\nThis is a test from the funding pipeline."
    for topic in topics:
        send_push(topic, title, body, priority="default")


def send_test_rich(topics: list[str]):
    """Send a rich test notification with clickable action buttons."""
    report_links = load_report_links()
    airops_url = report_links.get("airops", {}).get("drive_url", "")

    title = "AirOps raised $40M (Series B)"
    body = (
        "Contact: Alex Halliday (CEO)\n"
        "HQ: San Francisco + New York\n"
        "Employees: ~74-100 (doubling)\n"
        "What: AI content ops platform for SEO/marketing"
    )
    actions = []
    if airops_url:
        actions.append(f"view, Open Report, {airops_url}")
    actions.append("view, News Article, https://techcrunch.com/2025/11/10/airops-raises-40m-series-b-to-help-marketers-scale-ai-content/")
    actions.append("view, Alex Halliday (CEO), https://www.linkedin.com/in/alexhalliday/")
    for topic in topics:
        send_push(
            topic, title, body,
            priority="high",
            click_url=airops_url or actions[0].split(", ")[-1],
            actions=actions,
        )


def main():
    parser = argparse.ArgumentParser(description="Send push notifications for funding alerts")
    parser.add_argument("--input", "-i", help="Path to funding results JSON file")
    parser.add_argument("--topics", "-t", default=",".join(DEFAULT_TOPICS),
                        help=f"Comma-separated ntfy topics (default: {','.join(DEFAULT_TOPICS)})")
    parser.add_argument("--test", action="store_true", help="Send a test notification")
    parser.add_argument("--test-rich", action="store_true", help="Send a rich test with clickable links")

    args = parser.parse_args()
    topics = [t.strip() for t in args.topics.split(",") if t.strip()]

    if args.test:
        send_test(topics)
    elif args.test_rich:
        send_test_rich(topics)
    elif args.input:
        notify_from_results(args.input, topics)
    else:
        print("[ERROR] Provide --input <file>, --test, or --test-rich")
        sys.exit(1)


if __name__ == "__main__":
    main()
