version: "3"

services:
  ntfy:
    image: binwiederhier/ntfy:latest
    container_name: ntfy-funding
    command: serve
    ports:
      - "8080:80"
    volumes:
      - ntfy-cache:/var/cache/ntfy
      - ./server.yml:/etc/ntfy/server.yml
    restart: unless-stopped

volumes:
  ntfy-cache:
